### ISSUE TITLE
Brew install issue on Mac OS X Yosemite

### ISSUE THREAD

**Issue by afressancourt** [tracebox/tracebox#17]
Hello,

I tried to install trace box on Mac OSX Yosemite using the homebrew method. Homebrew installs autoconf, automake, libtool and lua properly. When it comes to tracebox's turn, I get the following error:
==> make install
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I/usr/include/pcap -ansi -pedantic -Wall -g -O2 -c crafter/Utils/IPv4Parse.cpp -o crafter/Utils/IPv4Parse.o
make[3]: *** [all] Error 2
make[2]: *** [all-local] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

brew doctor returns no issue of some sort. 
I have noticed that when installing libtool, Homebrew states that it prefixes the lib's name by g to avoid conflicts with Apple's libtool version.  

I am alone in front of this issue? How can I get around the problem?

Thanks in advance

**Comment by gdetal** [comment]
Hello,

Unfortunately, I don't have Yosemite and so I cannot easily fix the issue. I will however try to update in the near future and hope it does not break anything ;-)

**Comment by afressancourt** [comment]
I tried to do a symlink for glibtool to libtool in /usr/local/bin/, it doesn't work either.

Take care when updating to Yosemite, it is by far the most broken Mac OSX update I have seen.

**Comment by oliviertilmans** [comment]
Hello,

Could you first try to build the package manually (./bootstrap.sh && ./configure && make) in order to see whether this is a problem with the homebrew formula or something else.

**Comment by afressancourt** [comment]
Hello,

Thanks for your answer, 
I will try to do that tomorrow and let you know about the results.

**Comment by afressancourt** [comment]
Hello,

I just tried to build the package manually. I get a compilation error, yet it seems that it comes from crafter rather than Tracebox:
> crafter/Utils/BitHandling.h:69:11: error: expected ')'
        uint64_t htonll(uint64_t value);
                 ^
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
crafter/Utils/BitHandling.h:69:11: note: to match this '('
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
In file included from crafter/Utils/BitHandling.cpp:28:
crafter/Utils/BitHandling.h:71:11: error: expected ')'
        uint64_t ntohll(uint64_t value);
                 ^
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
crafter/Utils/BitHandling.h:71:11: note: to match this '('
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
crafter/Utils/BitHandling.cpp:101:19: error: unexpected parenthesis after '::'
uint64_t Crafter::htonll(uint64_t value) {
                  ^
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
crafter/Utils/BitHandling.cpp:101:19: error: expected function body after function declarator
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
crafter/Utils/BitHandling.cpp:101:19: error: expected unqualified-id
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:78: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                                                                             ^
crafter/Utils/BitHandling.cpp:112:19: error: unexpected parenthesis after '::'
uint64_t Crafter::ntohll(uint64_t value) {
                  ^
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
crafter/Utils/BitHandling.cpp:112:19: error: expected function body after function declarator
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
crafter/Utils/BitHandling.cpp:112:19: error: expected unqualified-id
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:78: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                                                                             ^
8 errors generated.
make[4]: *** [crafter/Utils/BitHandling.lo] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-local] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

Thanks for your help !

**Comment by oliviertilmans** [comment]
Hello,

could you try to apply [this patch](https://www.info.ucl.ac.be/~otilmans/patchwork/0001-Bithandling-check-if-ntohll-.-is-defined-as-a-macro.patch) to libcrafter so we can see whether there are further errors down the line...
```
cd tracebox_dir/noinst/libcrafter
git apply path_to/0001-Bithandling-check-if-ntohll-.-is-defined-as-a-macro.patch
```

**Comment by afressancourt** [comment]
Hello,

I have a different error then, also on crafter/Utils/BitHandling.cpp:
> In file included from crafter/Utils/BitHandling.cpp:28:
crafter/Utils/BitHandling.h:74:11: error: expected ')'
        uint64_t ntohll(uint64_t value);
                 ^
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro
      '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
crafter/Utils/BitHandling.h:74:11: note: to match this '('
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro
      '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
1 error generated.
make[4]: *** [crafter/Utils/BitHandling.lo] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-local] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

I applied the patch either before or after doing the ./bootstrap.sh scripting phase.

**Comment by oliviertilmans** [comment]
My bad, I made a typo ...
I updated the patch file, simplest way for you to test it is to do a git reset then reapply the new one.

**Comment by afressancourt** [comment]
Hello,

The patch makes the compilation work, thanks a lot!

I applied the patch after the ./bootstrap.sh, and compilation went through. Let me know if you want me to provide you with the resulting binaries somewhere.

Thanks again for your help!

**Comment by oliviertilmans** [comment]
I've pushed that same patch on libcrafter & updated the master branch reference.

I have no idea whether this will fix the homebrew build, as I don't know whether it pulls the master branch or a tag.
