### ISSUE TITLE
Ipv6 only on nic gives errors

### ISSUE THREAD

**Issue by Namsep** [tracebox/tracebox#21]
Hi,

I have on my computer 2 network cards, one with a rfc1918 and the other with an IPv6 adres. This because I have 2 CPE's one for IPv4 and one for IPv6.

Doing a trace to an IPv6 destionation fails:
tracebox -6 www.google.com
terminate called after throwing an instance of 'std::runtime_error'
  what():  Packet::SendRecv() : Error getting device information p34p1: no IPv4 address assigned
Aborted (core dumped)

**Comment by gdetal** [comment]
Hi,

Can you try to manually specify the interface to use ? ```tracebox -6 -i <interface> www.google.com```

**Comment by Namsep** [comment]
I tried, same error. The interface with only the IPv6 adres is p34p1.

Adding an IPv4 adres to that interface fixes it. Just don't specify a (ipv4) gateway. Also specifying the interace is then no longer required. Quess that this a very specific situation.

**Comment by gdetal** [comment]
I'm keeping this issue open as it is definitely a bug :-)

The issue however lies in libcrafter that uses pcap_lookupnet. This function returns the IPv4 address and the netmask associated with an interface. The library should not use this function in the case of an IPv6 packet.

**Comment by oliviertilmans** [comment]
Will be fixed by https://github.com/pellegre/libcrafter/pull/19
