### ISSUE TITLE
The debian packaging produces a deb package without any binary in there

### ISSUE THREAD

**Issue by zoobab** [tracebox/tracebox#25]
The debian packaging produces a deb package without any binary in there, at least on wheezy:

$ debuild
 dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package tracebox
dpkg-buildpackage: source version 0.1
dpkg-buildpackage: source changed by Gregory Detal <gregory.detal@uclouvain.be>
 dpkg-source --before-build source
dpkg-buildpackage: host architecture amd64
 fakeroot debian/rules clean
dh clean  --with autotools-dev
   dh_testdir
   dh_auto_clean
   dh_autotools-dev_restoreconfig
	for c_g in `find -type f -name config.guess` ; do if test -e $c_g.dh-orig ; then mv -f $c_g.dh-orig $c_g ; fi ; done
	for c_s in `find -type f -name config.sub`   ; do if test -e $c_s.dh-orig ; then mv -f $c_s.dh-orig $c_s ; fi ; done
   dh_clean
	rm -f debian/tracebox.substvars
	rm -f debian/tracebox.*.debhelper
	rm -rf debian/tracebox/
	rm -f debian/*.debhelper.log
	rm -f debian/files
	find .  \( \( -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} \; \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} \; \) \)
 dpkg-source -b source
dpkg-source: warning: no source format specified in debian/source/format, see dpkg-source(1)
dpkg-source: warning: source directory 'source' is not <sourcepackage>-<upstreamversion> 'tracebox-0.1'
dpkg-source: info: using source format `1.0'
dpkg-source: info: building tracebox in tracebox_0.1.tar.gz
dpkg-source: info: building tracebox in tracebox_0.1.dsc
 debian/rules build
dh build  --with autotools-dev
   dh_testdir
   dh_autotools-dev_updateconfig
	for c_g in `find -type f -name config.guess` ; do if ! test -e $c_g.dh-orig ; then mv -f $c_g $c_g.dh-orig ; cp -f /usr/share/misc/config.guess $c_g ; fi ; done
	for c_s in `find -type f -name config.sub`   ; do if ! test -e $c_s.dh-orig ; then mv -f $c_s $c_s.dh-orig ; cp -f /usr/share/misc/config.sub   $c_s ; fi ; done
   dh_auto_configure
   dh_auto_build
   dh_auto_test
 fakeroot debian/rules binary
dh binary  --with autotools-dev
   dh_testroot
   dh_prep
	rm -f debian/tracebox.substvars
	rm -f debian/tracebox.*.debhelper
	rm -rf debian/tracebox/
   dh_installdirs
	install -d debian/tracebox
   dh_auto_install
   dh_install
   dh_installdocs
	install -g 0 -o 0 -d debian/tracebox/usr/share/doc/tracebox
   dh_installchangelogs
	install -o 0 -g 0 -p -m644 debian/changelog debian/tracebox/usr/share/doc/tracebox/changelog
   dh_installexamples
   dh_installman
   dh_installcatalogs
   dh_installcron
   dh_installdebconf
	install -o 0 -g 0 -d debian/tracebox/DEBIAN
   dh_installemacsen
   dh_installifupdown
   dh_installinfo
   dh_pysupport
dh_pysupport: This program is deprecated, you should use dh_python2 instead. Migration guide: http://deb.li/dhs2p
	/usr/share/python-support/private/movemodules debian/tracebox
   dh_installinit
   dh_installmenu
   dh_installmime
   dh_installmodules
   dh_installlogcheck
   dh_installlogrotate
   dh_installpam
   dh_installppp
   dh_installudev
   dh_installwm
   dh_installxfonts
   dh_installgsettings
   dh_bugfiles
   dh_ucf
   dh_lintian
   dh_gconf
   dh_icons
   dh_perl
   dh_usrlocal
   dh_link
   dh_compress
	cd debian/tracebox
	chmod a-x usr/share/doc/tracebox/changelog
	gzip -9nf usr/share/doc/tracebox/changelog
	cd '/root/source'
   dh_fixperms
	find debian/tracebox  -print0 2>/dev/null | xargs -0r chown --no-dereference 0:0
	find debian/tracebox ! -type l  -print0 2>/dev/null | xargs -0r chmod go=rX,u+rw,a-s
	find debian/tracebox/usr/share/doc -type f  ! -regex 'debian/tracebox/usr/share/doc/[^/]*/examples/.*' -print0 2>/dev/null | xargs -0r chmod 644
	find debian/tracebox/usr/share/doc -type d  -print0 2>/dev/null | xargs -0r chmod 755
	find debian/tracebox/usr/share/man debian/tracebox/usr/man/ debian/tracebox/usr/X11*/man/ -type f  -print0 2>/dev/null | xargs -0r chmod 644
	find debian/tracebox -perm -5 -type f \( -name '*.so.*' -or -name '*.so' -or -name '*.la' -or -name '*.a' \)  -print0 2>/dev/null | xargs -0r chmod 644
	find debian/tracebox/usr/include -type f  -print0 2>/dev/null | xargs -0r chmod 644
	find debian/tracebox/usr/share/applications -type f  -print0 2>/dev/null | xargs -0r chmod 644
	find debian/tracebox -perm -5 -type f \( -name '*.cmxs' \)  -print0 2>/dev/null | xargs -0r chmod 644
	find debian/tracebox/usr/lib/perl5 debian/tracebox/usr/share/perl5 -type f -perm -5 -name '*.pm'  -print0 2>/dev/null | xargs -0r chmod a-X
	find debian/tracebox/usr/lib -type f -name '*.ali'  -print0 2>/dev/null | xargs -0r chmod uga-w
   dh_strip
   dh_makeshlibs
	rm -f debian/tracebox/DEBIAN/shlibs
   dh_shlibdeps
   dh_installdeb
   dh_gencontrol
	echo misc:Depends= >> debian/tracebox.substvars
	dpkg-gencontrol -ldebian/changelog -Tdebian/tracebox.substvars -Pdebian/tracebox
dpkg-gencontrol: warning: Depends field of package tracebox: unknown substitution variable ${shlibs:Depends}
	chmod 644 debian/tracebox/DEBIAN/control
	chown 0:0 debian/tracebox/DEBIAN/control
   dh_md5sums
	(cd debian/tracebox >/dev/null ; find . -type f  ! -regex './DEBIAN/.*' -printf '%P\0' | LC_ALL=C sort -z | xargs -r0 md5sum > DEBIAN/md5sums) >/dev/null
	chmod 644 debian/tracebox/DEBIAN/md5sums
	chown 0:0 debian/tracebox/DEBIAN/md5sums
   dh_builddeb
	dpkg-deb --build debian/tracebox ..
dpkg-deb: building package `tracebox' in `../tracebox_0.1_amd64.deb'.
 dpkg-genchanges  >../tracebox_0.1_amd64.changes
dpkg-genchanges: including full source code in upload
 dpkg-source --after-build source
dpkg-buildpackage: full upload; Debian-native package (full source is included)
Now running lintian...
warning: the authors of lintian do not recommend running it with root privileges!
W: tracebox source: diff-contains-git-control-dir .git
W: tracebox source: no-debian-copyright
E: tracebox source: invalid-standards-version 0.1
E: tracebox: no-copyright-file
E: tracebox: description-starts-with-package-name
W: tracebox: spelling-error-in-description allows to allows one to
W: tracebox: empty-binary-package
Finished running lintian.
Now signing changes and any dsc files...
 signfile tracebox_0.1.dsc Gregory Detal <gregory.detal@uclouvain.be>
gpg: skipped "Gregory Detal <gregory.detal@uclouvain.be>": secret key not available
gpg: /tmp/debsign.bmwun3Tj/tracebox_0.1.dsc: clearsign failed: secret key not available
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1278:
running debsign failed

**Comment by gdetal** [comment]
have you tried: 
```
make debian-package
```

https://drone.io/github.com/tracebox/tracebox/files also contains a pre-built deb package.

**Comment by zoobab** [comment]
Do you know with what do I have to install to have "make debian-package"? Googling it and I cannot find much.

**Comment by oliviertilmans** [comment]
Hello,
Try to make a 'normal' build.
That is, make sure you have packages lua5.2 lua5.2-dev build-essential libpcap-dev autoconf

```
./bootstrap.sh [--enable-tests, [--prefix=..., [...]]]
make debian-package
```

For the original error, nothing was produced because nothing was built in the first place as debuild errored because it could not find the gpg key of Gregory (sigh) as he's the most recent in the changelog.

**Comment by zoobab** [comment]
The 'normal' and standard way of doing debian packages is to use debuild, and do not rely on custom make scripts from upstream. So ./bootstrap + make debian-package is a no go.

**Comment by oliviertilmans** [comment]
I've forced debhelper to run autoreconf when called, as make debian-package will be called by it anyway. Packaging with debuild succeeded on a test vm with wheezy, feel free to to reopen if needed.
