### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by Stevenson29** [tracebox/tracebox#31]
I'm running tracebox on a ubuntu 64bits machine. I intent to use it as part of my final project in university, but I've been facing this issue for a few days and I can't find a solution. Tracebox was working perfectly, when suddenly it stopped returning any IP but hop number 5. Using default or specific probes. If I Use UDP probes it works partially but never reach the destination (it goes until the very last hop, but doesn't stop). This is the output that I'm getting:
<pre>
<code>
root@ip-172-31-18-123:/var/www/cgi-bin# tracebox -n 8.8.8.8
tracebox to 8.8.8.8 (8.8.8.8): 64 hops max
1: *
2: *
3: *
4: *
5: 54.239.48.178 IP::TTL IP::CheckSum
6: *
7: *
8: *
9: *
10: *
11: *
12: *
13: *
14: *
15: *
^C
root@ip-172-31-18-123:/var/www/cgi-bin# tracebox -n -p 'IP/UDP' 8.8.8.8
tracebox to 8.8.8.8 (8.8.8.8): 64 hops max
1: *
2: *
3: *
4: 100.64.16.89 IP::TTL IP::CheckSum
5: 205.251.232.223 IP::TTL IP::CheckSum
6: 205.251.232.216 IP::TTL IP::CheckSum
7: 205.251.232.78 IP::TTL IP::CheckSum
8: 205.251.225.185 IP::TTL IP::CheckSum
9: 72.14.219.251 IP::TTL IP::CheckSum
10: 72.14.233.3 IP::DiffServicesCP IP::TTL IP::CheckSum
11: *
12: *
13: *
14: *
15: *
16: *
^C
</code>
</pre>
In this case hop 11 would be 8.8.8.8. If you can give me any ideas that'd be great. The main issue it to make it work with defaul probes. Thanks in advance.

**Comment by oliviertilmans** [comment]
Hello,

Which version are you running ? One of the tagged ones or the latest commit on master ?
Could you try to use the latest one if possible ?

**Comment by oliviertilmans** [comment]
Here are some details about the probes:
The default probe is an IPv4/TCP(syn) one, targeting port 80. Targeting the google anycast dns service is probably not the best target for it as they probably don't have process listening on that port. Same goes for the UDP one. Depending on their configuration, they might not echo back an ICMP port unreachable when reaching the destination.

```
sudo bin/bin/tracebox -d 53 8.8.8.8 
tracebox to 8.8.8.8 (8.8.8.8): 64 hops max
1: gateway (130.104.228.126) 
2: CtPythagore.sri.ucl.ac.be (130.104.254.229) IP::TTL IP::CheckSum 
3: ge.cr2.brueve.belnet.net (193.191.3.85) IP::TTL IP::CheckSum 
4: 10ge.cr1.brueve.belnet.net (193.191.16.21) IP::TTL IP::CheckSum 
5: 195.66.224.125 (195.66.224.125) IP::TTL IP::CheckSum 
6: 216.239.47.109 (216.239.47.109) IP::DiffServicesCP IP::TTL IP::CheckSum 
7: 216.239.48.107 (216.239.48.107) IP::DiffServicesCP IP::TTL IP::CheckSum 
8: google-public-dns-a.google.com (8.8.8.8) 
```
Notice that I explicitely targeted the DNS port (-d 53).

If you want a more precise control on what do the probe contain, I'd advise you to at least always use the -p options, e.g. -p 'IP/tcp{dst=53}'.

If you want an almost guaranteed answer by your target, you can always use the standard ping payload, e.g. -p 'IP/ICMPEchoReq(1,1)'

**Comment by Stevenson29** [comment]
Hello Olivier, thanks very much for your comments. Actually I'm not using the latest version, but I'll install it and come back here to tell what happened.

About the destination port, I've tried what you suggested, even before creating this topic, the result was the same. I used 8.8.8.8 here just as an example, I tried to send probes to many different addresses and the results were the same. 

With the standard ping payload ('IP/ICMPEchoReq(1,1)'), I got some answers, but only <code> IP::TTL IP::CheckSum </code>. I'm really interested here in finding middleboxes performing modifications on TCP options (I was using probes with TCP option before the problem).

I'll be back here soon to comment about the new version, and tell if it worked or not.

**Comment by Stevenson29** [comment]
Hello Olivier, thanks very much for your comments. Actually I'm not using the latest version, but I'll install it and come back here to tell what happened.

About the destination port, I've tried what you suggested, even before creating this topic, the result was the same. I used 8.8.8.8 here just as an example, I tried to send probes to many different addresses and the results were the same. 

With the standard ping payload ('IP/ICMPEchoReq(1,1)'), I got some answers, but only <code> IP::TTL IP::CheckSum </code>. I'm really interested here in finding middleboxes performing modifications on TCP options (I was using probes with TCP option before the problem).

I'll be back here soon to comment about the new version, and tell if it worked or not.

**Comment by Stevenson29** [comment]
Hello Olivier, thanks very much for your comments. Actually I'm not using the latest version, but I'll install it and come back here to tell what happened.

About the destination port, I've tried what you suggested, even before creating this topic, the result was the same. I used 8.8.8.8 here just as an example, I tried to send probes to many different addresses and the results were the same. 

With the standard ping payload ('IP/ICMPEchoReq(1,1)'), I got some answers, but only <code> IP::TTL IP::CheckSum </code>. I'm really interested here in finding middleboxes performing modifications on TCP options (I was using probes with TCP option before the problem).

I'll be back here soon to comment about the new version, and tell if it worked or not.

**Comment by Stevenson29** [comment]
Well, no luck so far. The problem remains, even with the new version. Me and my supervisor have tried many different configurations on the server but the problem persists. Do you have any other advice that we can try to make this work?
Thanks

**Comment by oliviertilmans** [comment]
The easiest for me would be to know what you are targeting with what kind of probes, as at present I cannot reproduce your errors.
An alternative would also to try an old version (https://github.com/tracebox/tracebox/releases/tag/v0.2) but it has other bugs (although they might not manifest if you restrict yourself to sample probes).

One critical part when testing TCP options is to ensure that you add the proper padding in the options (via nop()/eol()) in order to round up the total header length.

**Comment by Stevenson29** [comment]
I understand your point. We are trying to use probes with TCP options and observe what kind of modifications tracebox will detect, specially regarding to MPCAPABLE. As a alternative, I could give you access to our server, so you could check it yourself to be able to see the problem.

**Comment by oliviertilmans** [comment]
This should normally work as-is (e.g. à-la tracebox -p IP/TCP/MPCAPABLE www.domain.com), as long as you target the proper ip address/tcp dst port.

Could you please let my know the following versions:
- kernel ($ uname -a)
- git revision in use ($ git rev-parse HEAD)
- libpcap ($ dpkg -s libpcap)
- lua (lua -v)

**Comment by Stevenson29** [comment]
Hi, Versions:

Kernel: 3.13.0-46-generic
Git: git version 1.9.1
libcap: libpcap-dev (1.5.3-2) and libpcap0.8 (1.5.3-2)
Lua: Lua 5.2.3

**Comment by oliviertilmans** [comment]
Thanks!

Almost there but we're missing the most important one, the git revision (commit id):
```
$ cd tracebox_dir
$ git rev-parse HEAD
```

**Comment by Stevenson29** [comment]
I did exactly what you said and the command line on the tracebox dir returned:
b3bdc5f45849a3492c680112ea8367a2d3fed5fe

Anyway, I think the problem must be in the network, and if so, I'll have to find an alternative to use tracebox.

**Comment by Stevenson29** [comment]
I did exactly what you said and the command line on the tracebox dir returned:
<code><pre>b3bdc5f45849a3492c680112ea8367a2d3fed5fe</code></pre>
Anyway, I think the problem must be in the network, and if so, I'll have to find an alternative to use tracebox.

**Comment by Stevenson29** [comment]
If instead of letting tracebox send the default probe I choose to specify this probe, would it be as simple as: tracebox -p 'IP/TCP' www.example.com ?

**Comment by oliviertilmans** [comment]
Yes. That will build a probe made of an ipv4 header followed by a TCP header with destination port 80 and the SYN flag

**Comment by Stevenson29** [comment]
Ok, thanks.

**Comment by Stevenson29** [comment]
Ok, thanks.
