### ISSUE TITLE
IPv6: not resolving intermediate hops

### ISSUE THREAD

**Issue by c92xteaj** [tracebox/tracebox#37]
Hi,

I am not sure, if it is due to my network setup or if I am not using tracebox correctly on IPv6.
Thing is, that on a route via IPv6 <1> I do not get reports forintermediate hops, while I see package checksums updates via IPv4 <2>. I would expect, that both routes/elements on the route should be the same in their behaviour?
(I still have to figure out the different number of hops...)

One suspicion is, that the name resolution plays a role? For the intermediate IPv6 hops, the addresses are not resolved with plain traceroute6 <3> (IPv4 and IPv6 nameservers are enabled)

Cheers and thanks,
  Thomas

<1>
> tracebox  -6 -d XXXX xxxx-ipv6.ndgf.org
tracebox to 2001:948:40:xxxx::xxxx (xxxx-ipv6.ndgf.org): 64 hops max
1: 2a00:1398:107:6b65::1 (2a00:1398:107:6b65::1) 
2: *
3: *
4: *
5: *
6: xxxx.ndgf.org (2001:948:40:xxxx::xxxx) TCP::SrcPort TCP::DstPort TCP::SeqNumber TCP::AckNumber TCP::Flags TCP::WindowsSize TCP::CheckSum IPv6::HopLimit IPv6::SourceIP IPv6::DestinationIP 

<2>
> tracebox  -d XXXX xxxx-ipv4.ndgf.org
tracebox to 109.105.xxx.xxx (xxxx-ipv4.ndgf.org): 64 hops max
1: tr-v740-rig2.gridka.de (192.108.46.242) 
2: l513-e-rbrxl-2-re9.cern.ch (192.16.166.37) IP::TTL IP::CheckSum 
3: l513-e-rbrxl-1-tl0.cern.ch (192.16.166.145) IP::TTL IP::CheckSum 
4: dk-ore.nordu.net (192.16.166.50) IP::TTL IP::CheckSum 
5: xxxx.ndgf.org (109.105.xxx.xxx) TCP::SrcPort TCP::DstPort TCP::SeqNumber TCP::AckNumber TCP::Flags TCP::WindowsSize TCP::CheckSum IP::TTL IP::CheckSum IP::SourceIP IP::DestinationIP 

<3>
> traceroute -6 xxxx-ipv6.ndgf.org
traceroute to xxxx-ipv6.ndgf.org (2001:948:40:xxx::xxx), 30 hops max, 80 byte packets
 1  2a00:1398:107:6b65::1 (2a00:1398:107:6b65::1)  1.773 ms  1.773 ms  1.780 ms
 2  2a00:1398:106:5::2 (2a00:1398:106:5::2)  1.369 ms  1.413 ms  1.478 ms
 3  2001:1458:302:d::1 (2001:1458:302:d::1)  30.082 ms  30.146 ms  30.194 ms
 4  2001:1458:302:24::1 (2001:1458:302:24::1)  20.840 ms  20.828 ms  20.811 ms
 5  2001:1458:302:f::2 (2001:1458:302:f::2)  41.379 ms  41.431 ms  41.420 ms
 6  xxxx.ndgf.org (2001:948:40:xxx::xxx)  41.428 ms  41.228 ms  41.173 ms

**Comment by oliviertilmans** [comment]
Hello,
The * indicates that a timeout was encoutered when waiting for a reply (icmp time exceeded or real) answer for a probe with a hop limit of e.g. 3 (in case of 3: *).
In your case, I'd guess that this is due to the code filtering out incoming packets that is too restrictive and ignores incoming packets it shouldn't.
I'm currently trying to loosen up that code, should be out 'soon'.

**Comment by oliviertilmans** [comment]
Hello, could you try to checkout the branch pcap_filter , It should now accepts more ICMP replies, if any.
```bash
$ git checkout pcap_filter
$ make
($sudo make install)
```

Thanks!

**Comment by c92xteaj** [comment]
Hi,

with commit e679619f94b9e1e in branch pcap_filter tracebox is more
verbose on IPv6

Cheers and thanks,
  Thomas

> tracebox -6 -d xxxx xxxx-ipv6.ndgf.org
tracebox to 2001:948:40:xxx::xxx (xxxx-ipv6.ndgf.org): 64 hops max
1: 2a00:1398:107:6b65::1 (2a00:1398:107:6b65::1)
2: 2a00:1398:106:5::2 (2a00:1398:106:5::2) TCP::SeqNumber TCP::CheckSum
IPv6::HopLimit
3: 2001:1458:302:d::1 (2001:1458:302:d::1) TCP::SeqNumber TCP::CheckSum
IPv6::HopLimit
4: 2001:1458:302:24::1 (2001:1458:302:24::1) TCP::SeqNumber
TCP::CheckSum IPv6::HopLimit
5: 2001:1458:302:f::2 (2001:1458:302:f::2) TCP::SeqNumber TCP::CheckSum
IPv6::HopLimit
6: xxxx.ndgf.org (2001:948:40:xxx::xxx) TCP::SrcPort TCP::DstPort
TCP::SeqNumber TCP::AckNumber TCP::DataOffset TCP::Flags
TCP::WindowsSize TCP::CheckSum IPv6::PayloadLength IPv6::HopLimit
IPv6::SourceIP IPv6::DestinationIP +TCPOptionMaxSegSize


> tracebox -d xxxx -6 xxxx.csc.fi
tracebox to 2001:708:10:xxxx::xxxx (xxxx.csc.fi): 64 hops max
1: 2a00:1398:107:6b65::1 (2a00:1398:107:6b65::1)
2: 2a00:1398:106:5::2 (2a00:1398:106:5::2) TCP::SeqNumber TCP::CheckSum
IPv6::HopLimit
3: 2a00:1398:106:2::1 (2a00:1398:106:2::1) TCP::SeqNumber TCP::CheckSum
IPv6::HopLimit
4: tr-v700-rircn1.scc.kit.edu (2a00:1398:106:1::1) TCP::SeqNumber
TCP::CheckSum IPv6::HopLimit
5: cr-fra1-te0-7-0-3-1906.x-win.dfn.de (2001:638:c:a154::1)
TCP::SeqNumber TCP::CheckSum IPv6::HopLimit
6: cr-tub1-hundredgige0-1-0-0-7.x-win.dfn.de (2001:638:c:c007::1)
TCP::SeqNumber TCP::CheckSum IPv6::HopLimit
7: dfn.mx1.ams.nl.geant.net (2001:798:18:10aa::11) TCP::SeqNumber
TCP::CheckSum IPv6::HopLimit
8: nordunet-bckp2-gw.mx1.ams.nl.geant2.net (2001:798:22:10aa::a)
TCP::SeqNumber TCP::CheckSum IPv6::HopLimit
9: dk-ore.nordu.net (2001:948:1:e::2) TCP::SeqNumber TCP::CheckSum
IPv6::HopLimit
10: se-fre.nordu.net (2001:948:1:28::3) TCP::SeqNumber TCP::CheckSum
IPv6::HopLimit
11: ndn-gw.funet.fi (2001:948:3:b::3) TCP::SeqNumber TCP::CheckSum
IPv6::HopLimit
12: csc2-xe-0-0-0-0-csc6.funet.fi (2001:708:0:f000:0:60:20:2)
TCP::SeqNumber TCP::CheckSum IPv6::HopLimit
13: xxxx.csc.fi (2001:708:10:xxx::xxx) TCP::SrcPort TCP::DstPort
TCP::SeqNumber TCP::AckNumber TCP::DataOffset TCP::Flags
TCP::WindowsSize TCP::CheckSum IPv6::PayloadLength IPv6::HopLimit
IPv6::SourceIP IPv6::DestinationIP +TCPOptionMaxSegSize

**Comment by oliviertilmans** [comment]
Good, I'll get this merged into master asap.
Thanks for the feedback!
