### ISSUE TITLE
lua build error

### ISSUE THREAD

**Issue by shpank** [tracebox/tracebox#42]
When building tracebox from source under Debian Wheezy, I get the following error message when running make in src/tracebox:

```
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../noinst/libcrafter/libcrafter -I/usr/include/lua5.1 -I/usr/include  -fno-omit-frame-pointer -Wall    -g -O2 -std=gnu++11 -c -o tracebox-lua.o `test -f 'lua.cc' || echo './'`lua.cc
In file included from lua/lua_packet.hpp:11:0,
                 from lua.cc:9:
lua/lua_crafter.hpp:94:18: error: ‘l_ref<Base>::l_ref’ names constructor
lua/lua_crafter.hpp:132:26: error: ‘l_crafter_ref<C>::l_crafter_ref’ names constructor
In file included from lua.cc:9:0:
lua/lua_packet.hpp:14:40: error: ‘l_crafter_ref<Crafter::Packet>::l_crafter_ref’ names constructor
make[5]: *** [tracebox-lua.o] Error 1
```

Any pointers on where it went wrong?

**Comment by oliviertilmans** [comment]
Hello,

My first guess would be that you're using gcc < 4.8, could that be the case ? 
The code is slowly moving to cxx11 hence the requirement on gcc 4.8, and it appears to be failing on the using directive.
I guess I should add a build dependency on gcc (>= 4.8) in the debian/control file.

**Comment by shpank** [comment]
That was the case. Thanks for the quick response!
