### ISSUE TITLE
Tracebox problems

### ISSUE THREAD

**Issue by aygkhn** [tracebox/tracebox#44]
Hello i am using multipath tcp. but when we write: sudo tracebox -n -p IP/TCP/MSS/MPCAPABLE multipath-tcp.org
our result:
how can we solve this problem?
mpathproject@mpathprojectpc:~$ sudo tracebox -n -p IP/TCP/MSS/MPCAPABLE multipath-tcp.org
tracebox to 130.104.230.45 (multipath-tcp.org): 64 hops max
1: *
2: *
3: *
4: *
5: 130.104.230.45 TCP::SrcPort TCP::DstPort TCP::SeqNumber TCP::AckNumber TCP::DataOffset TCP::Flags TCP::CheckSum IP::TotalLength IP::Identification IP::TTL IP::CheckSum IP::SourceIP IP::DestinationIP -TCPOptionMPTCPCapable 
Could not store results on server: Timeout was reached

**Comment by oliviertilmans** [comment]
Hello,

You can avoid the Timeout error using the -q flag (I guess you compiled tracebox with curl support).

Regarding the empty trace, could send me the resulting file (capture.pcap) after running:
```bash
tcpdump -I any icmp -w capture.pcap &
TCPDUMP_PID=$!
tracebox -n -p IP/TCP/MSS/MPCAPABLE/WSCALE multipath-tcp.org
kill $TCPDUMP_PID
```
This will allow me to check if there's a bug in the ICMP filers used by tracebox, or if all your intermediate hops are not sending the ICMP messages (I'd guess for the former case).

Thanks!

**Comment by aygkhn** [comment]
mpathproject@mpathprojectpc:~$ sudo tracebox -n -p -q IP/TCP/MSS/MPCAPABLE/WSCALE multipath-tcp.org
Lua error: [string "pkt=-q"]:1: attempt to perform arithmetic on global 'q' (a nil value)

**Comment by oliviertilmans** [comment]
My bad, should have checked the answer ...
-q should come before -p
```
tracebox -n -q -p IP/TCP/MSS/MPCAPABLE/WSCALE multipath-tcp.org
```

**Comment by aygkhn** [comment]
tracebox to 130.104.230.45 (multipath-tcp.org): 64 hops max
1: *
2: *
3: 193.140.41.10 IP::TTL IP::CheckSum 
4: 130.104.230.45 TCP::SrcPort TCP::DstPort TCP::SeqNumber TCP::AckNumber TCP::DataOffset TCP::Flags TCP::CheckSum IP::TotalLength IP::Identification IP::TTL IP::CheckSum IP::SourceIP IP::DestinationIP -TCPOptionMPTCPCapable TCPOptionWindowScale::Shift

**Comment by oliviertilmans** [comment]
I'd need to have the capture.pcap file that was generated by the script I wrote above if I want to understand why you get timeouts at hop 1 & 2.
In any case it looks like you have a TCP proxy at 193.140.41.10 that could be stripping the MPTCP options, since you're skipping all hosts between that hop and the last one (including our routers before multipath-tcp.org)
