### ISSUE TITLE
paralell tracebox sessions mix up

### ISSUE THREAD

**Issue by masgo** [tracebox/tracebox#46]
If you run two or more tracebox at the same time the results will mix up. This happens even I specify different pcap files for each instance. 

How to reproduce:
run `sudo tracebox -n -f pcap1 8.8.8.8` in one console and wait for the * * * to appear
now run `sudo tracebox -n -f pcap2 8.8.8.8` in another console.
The answers belonging to the second instance will appear in the first one. 
This does not happen every time but you should see the result after 2-3 tries.
This also happens when I use different targets.

Here is a sample output (I censored the first hops for privacy reasons):
```
tracebox to 8.8.8.8 (8.8.8.8): 64 hops max

5: 82.195.78.50  [PARTIAL] IP::TTL IP::CheckSum
6: 82.195.78.41  [PARTIAL] IP::TTL IP::CheckSum
7: 82.195.67.165 IP::TTL IP::CheckSum
8: 82.195.67.213  [PARTIAL] IP::TTL IP::CheckSum
9: 82.195.67.254  [PARTIAL] IP::TTL IP::CheckSum
10: *
11: *
12: *
13: *
14: *
15: *
16: *
17: *
18: *
19: *
20: *
21: *
22: 82.195.78.41  [PARTIAL] TCP::SrcPort TCP::SeqNumber IP::TTL IP::CheckSum
23: 82.195.67.165 TCP::SrcPort TCP::SeqNumber TCP::CheckSum IP::TTL IP::CheckSum
24: *
```

As one can see hop 22 and 23 re-appear. This is because of the second process.

**Comment by oliviertilmans** [comment]
Hi,

Could you check against rev. a767c6b064d8c9480abc20cbb3429d919fb3cb71 ?
The issue is that since both your sessions are using the same probes,
the pcap filters are having an hard time to differentiate between the
two "tracebox sessions". That patch should add enough infos to
distinguish them from each other.

**Comment by masgo** [comment]
Works for me, bug is fixed.Thank you.
