### ISSUE TITLE
Fedora dependencies

### ISSUE THREAD

**Issue by almereyda** [tracebox/tracebox#47]
I have successfully managed to `./configure` with the following dependencies installed

    dnf install autoconf automake libtool lua-devel libpcap-devel json-c-devel gnutls-devel lua-ldoc libnetfilter_queue-devel

**Comment by oliviertilmans** [comment]
Thanks for the report!

Could you tell me which version of Fedora you are running ? That way I can update the docs with all information.

**Comment by almereyda** [comment]
It is Fedora 24, but I suppose the packages exist at least down to 22.

**Comment by oliviertilmans** [comment]
Thank you !
