### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [tracebox/tracebox#52]
Based on https://github.com/tracebox/tracebox/releases and https://github.com/tracebox/tracebox/releases/latest I cannot tell if 0.3.1, 0.4.1, or something else besides either of them, is the current stable version.

Which version should be in Homebrew's `stable` spec? Thanks!

**Comment by oliviertilmans** [comment]
Hi,

Github apparently expects more than just a tag to mark it as a release (?), I pushed a new one for the current version and used their GUI ...

As a side note, not having a mac anymore, it is hard for me to ensure that everything still works as expected on the latest version (see #29 ...). The `make check` target should be a good indicator (if the Click router is still able to run on macOS ...).

**Comment by ilovezfs** [comment]
>Github apparently expects more than just a tag to mark it as a release (?)

Yep. The only way around that is to delete _all_ explicit releases but it's "better" to just explicitly create them.

>As a side note, not having a mac anymore, it is hard for me to ensure that everything still works as expected on the latest version (see #29 ...). The make check target should be a good indicator (if the Click router is still able to run on macOS ...).

OK, I will try `make check`

**Comment by ilovezfs** [comment]
@oliviertilmans any idea how to make the `-dirty` go away in the version given I'm building directly from the tag?

(Yes `make check` passes`)

**Comment by oliviertilmans** [comment]
See 5ee627c
i.e. remove the `--dirty` flag from `configure.ac`

**Comment by ilovezfs** [comment]
Thanks @oliviertilmans!

**Comment by ilovezfs** [comment]
@oliviertilmans voilà https://github.com/Homebrew/homebrew-core/pull/18830.

**Comment by oliviertilmans** [comment]
Thanks!
