### ISSUE TITLE
no IP ID randomized 

### ISSUE THREAD

**Issue by gdavila** [tracebox/tracebox#58]
Hello,

The `IP identification` value are not being set correctly if any other IP fields are manually setting (ip {dscp =0, ecn = 1}):

i. e. ,
`$ sudo tracebox -t 2 -p "ip {dscp =0, ecn = 1} / udp { src = 33456, dst = 33457}" 8.8.8.8`

sent probe (wireshark output): 
```
Internet Protocol Version 4, Src: 192.168.0.242, Dst: 8.8.8.8
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x01 (DSCP: CS0, ECN: ECT(1))
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..01 = Explicit Congestion Notification: ECN-Capable Transport codepoint '01' (1)
    Total Length: 28
    Identification: 0x0000 (0)
```

What I see on wireshark is that IP id always remain 0x0000 for all probes (even for different destination address and src ports). However, if not IP fields are  manually setting this doesn't happen (i.e., `$ sudo tracebox -t 2 -p "IP / udp { src = 33456, dst = 33457}" 8.8.8.8`).

This causes that when I send tb probes in parallel  all the replies get mixed.

I checked this issue on *ubuntu-server 16.04.3 LTS* and and *Raspbian GNU/Linux 9.1 (stretch)*. However, on *MacOS High Sierra* the bug doesn't occur (I mean, the IP id seems to be correctly  setting to a random value). 

tested tracebox version: `v0.4.2-16-gf3070ecaa84c80b2`

Let me know any thoughts.

**Comment by oliviertilmans** [comment]
AFAIK this has always been the case--The IP-related crafting parts in both libcrafter and tracebox haven't changed in years.

* `ip {} ` _constructs_ a new IPv4 layer from the given parameter, [0-initializing everything](https://github.com/tracebox/tracebox/blob/master/src/tracebox/lua/lua_ip.cpp#L61)

* `IP` is a _default_ IPv4 layer, [with an already set random ID](https://github.com/tracebox/tracebox/blob/master/src/tracebox/lua/lua_init.cpp#L265)

Actual IP addresses, IHL, checksums, TLL, are set on the fly at a later stage.

FreeBSD/macOS kernel will ensure that the IP ID field is never 0, so tracebox sets it anyway in that case (to ensure reproducible traces), but IIRC that's not a forbidden value even in RFC6864 hence allowed it when possible.

**Comment by gdavila** [comment]
Clear enough. As a solution to my issue  I just should be sure that first  my script set a random IP ID value to 'ip {}' constructor.

**Comment by oliviertilmans** [comment]
I've made this homogeneous across platforms anyway, a null IP ID can still be set explicitly on Linux if desired.
