### ISSUE TITLE
Tracebox always show 2 hops to every host

### ISSUE THREAD

**Issue by ammarbajwa** [tracebox/tracebox#59]
Every time I run tracebox for any domain name it always gives me 2 hops. Could you please tell what would be the reason behind it?? 

This is the command i give:
sudo ./tracebox amazon.com
tracebox to 176.32.98.166 (amazon.com): 64 hops max
1: 10.130.0.1 (10.130.0.1) 1ms IP::TTL IP::CheckSum 
2: 176.32.98.166 (176.32.98.166) 1ms TCP::SrcPort TCP::DstPort TCP::SeqNumber TCP::AckNumber TCP::DataOffset TCP::Flags TCP::WindowsSize TCP::CheckSum IP::TotalLength IP::Identification IP::TTL IP::CheckSum IP::SourceIP IP::DestinationIP +TCPOptionMaxSegSize

**Comment by oliviertilmans** [comment]
This indicates that you are behind a proxy (i.e., a host that is terminating your connection on one hand and opening a new one towards your real destination, then relaying the data).

**Comment by ammarbajwa** [comment]
Okay. I get that but then why does traceroute shows the hops but tracebox does not. Can you suggest a workaround for this problem.

**Comment by oliviertilmans** [comment]
It depends on the type of payload used by the traceroute implementation you have.

Change your probe type, as the default one is TCP which is likely behind that proxy.
E.g.,:
* `tracebox -p IP/UDP`
* `tracebox -p 'IP/ICMP.new{type=8, code=0, id=12345, seqno=1}'` (for a ping payload)

**Comment by ammarbajwa** [comment]
Okay sir. I had to use TCP but I guess I will have to use a different service provider. Thankyou very much for the prompt response.
