### ISSUE TITLE
Lua Includes not found 

### ISSUE THREAD

**Issue by alinaSarwar** [tracebox/tracebox#60]
Hi Olivier,

I was trying to add some prints in your code and after it when called make again then I get the following error:

**g++ -DHAVE_CONFIG_H -I. -I../..  -I../../noinst/libcrafter/libcrafter -I/usr/include/lua5.2 -I/usr/include/pcap  -fno-omit-frame-pointer -Wall    -g -O2 -std=gnu++11 -MT tracebox-lua.o -MD -MP -MF .deps/tracebox-lua.Tpo -c -o tracebox-lua.o `test -f 'lua.cc' || echo './'`lua.cc
In file included from lua/lua_crafter.hpp:11:0,
                 from lua/lua_packet.hpp:11,
                 from lua.cc:9:
lua/lua_base.hpp:16:19: fatal error: lua.hpp: No such file or directory
compilation terminated.**

I then tried to ./configure again and it said:

**checking if LUA_VERSION is defined... yes
checking lua.h usability... no
checking lua.h presence... no
checking for lua.h... no
checking lualib.h usability... no
checking lualib.h presence... no
checking for lualib.h... no
checking lauxlib.h usability... no
checking lauxlib.h presence... no
checking for lauxlib.h... no
checking luaconf.h usability... no
checking luaconf.h presence... no
checking for luaconf.h... no
configure: error: cannot find Lua includes**

I am unable to understand as why this problem would have come as a few days earlier I was making the tracebox again and again with little changes. I then even cloned the tracebox again into another directory but these errors still persist.

**Comment by alinaSarwar** [comment]
Got it running by reinstalling the lua libraries. Dont know though why such an error would come up as I could make the file previously. Sorry to disturb you sir.

**Comment by oliviertilmans** [comment]
Glad you could resolve this.

If this happens again, check the include paths in your gcc lines:
`ls /usr/include/lua5.2`

Some package upgrade/... could have broken it temporarily or moved it
out of the default gcc include path?
